import type { PaginatedResponse, PaginationRequestParams } from '@/types';

export type Product = {
  id: number;
  name: string;
  description: string;
  imageUrl: string;
  price: number;
};

export type PaginatedProductsResponse = PaginatedResponse<Product>;

export type ProductRequestParams = {
  category?: number;
  productId?: string;
} & PaginationRequestParams;

export type Category = {
  id: number;
  name: string;
  url: string;
  autogeneratedSlug: string;
  description: string;
  parentId?: number;
};

export type PaginatedCategoriesResponse = PaginatedResponse<Category>;

export type CategoryRequestParams = {
  parent?: number;
} & PaginationRequestParams;
