export type PaginatedResponse<T> = {
  items: T[];
  total: number;
  offset: number;
  limit: number;
};

export type Product = {
  id: number;
  name: string;
  description: string;
  imageUrl: string;
  price: number;
};

export type PaginatedProductsResponse = PaginatedResponse<Product>;

export type ProductRequestParams = {
  category?: number;
  limit?: number;
  offset?: number;
};

export type Category = {
  id: number;
  name: string;
  url: string;
  autogeneratedSlug: string;
  description: string;
  parentId?: string;
};

export type PaginatedCategoriesResponse = PaginatedResponse<Category>;
